server:
  port: 8080

management:
  endpoints:
    web.exposure.include: '*'

logging:
  level:
    org.springframework.cloud.gateway: trace

spring:
  application:
    name: new-api-gateway

  cloud:
    gateway:
      routes:
        - id: new-customer-service
          uri: lb://new-customer-service
          predicates:
            - Path=/customers/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: SERVICE_UNAVAILABLE
            - name: AddResponseHeader
              args:
                name: x-response-foo
                value: bar




