server:
  port: 8080

management:
  endpoints:
    web.exposure.include: '*'

logging:
  level:
    org.springframework.cloud.gateway: trace

spring:
  application:
    name: new-api-gateway

  cloud:
    gateway:
      routes:
        - id: new-customer-service
          uri: lb://new-customer-service
          predicates:
            - Path=/customers/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@userKeyResolver}'
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 2
            - name: Retry
              args:
                retries: 3
                statuses: SERVICE_UNAVAILABLE
            - AddResponseHeader=X-Some-Header, foo

        - id: legacy-service
          uri: lb://legacy-service
          predicates:
            - Path=/legacy/exposed




