spring:
  application:
    name: new-customer-service

logging:
  level:
    org.springframework: info
    io.github.resilience4j: debug

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: '*'


