spring:
  application:
    name: customer-service

server:
  port: 9090

logging:
  level:
    org.springframework.cloud: trace

# default hystrix timeout is 1000ms
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000